blank_issues_enabled: false
contact_links:
  - name: OJS questions not related to this theme
    url: https://forum.pkp.sfu.ca/
    about: Ask general Open Journal Systems questions on the PKP Community Forum.
